title: Supporto Tecnico RT-POS 2026
description: Documentazione Normativa Scambio Importo 26 - Custom SpA
theme: jekyll-theme-cayman # Tema base compatibile con personalizzazioni rapide

# Personalizzazioni
logo: /logo.png
font: Titillium Web

# Impostazioni di pubblicazione
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme