title: "Obbligo collegamento POS - RT 2026"
description: "Documentazione Normativa Scambio Importo 26 - Custom SpA"
url: "https://ivanrobuschi-custom.github.io"
baseurl: "/COLLEGAMENTO-POS_RT-2026" # Nome esatto della tua cartella repository

# Configurazione Tema
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "air" # Una skin pulita, adatta a manuali tecnici

# Impostazioni Generali
locale: "it-IT"
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

# Gestione Sidebar (Menu laterale)
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      sidebar:
        nav: "docs" # Punta alla navigazione che creeremo nel prossimo stepe

# Aggiungi o modifica queste righe nel _config.yml
logo: "/logo.png"
masthead:
  title: "" # Lascia vuoto se il logo contiene gi√† il nome "Custom"
sass:
  style: compressed